name: Deploy Website via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1     # change if needed

      - name: Create deployment bundle
        run: |
          zip -r website.zip index.html assets css js appspec.yml

      - name: Upload bundle to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          export S3_BUCKET="gitactiion1535"    # change to YOUR bucket
          export S3_KEY="artifacts/website-$TIMESTAMP.zip"
          aws s3 cp website.zip s3://$S3_BUCKET/$S3_KEY
          echo "S3_KEY=$S3_KEY" >> $GITHUB_ENV

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name portfolio-app \
            --deployment-group-name portfolio-dg \
            --s3-location bucket=gitactiion1535,key=${{ env.S3_KEY }},bundleType=zip

